# Generated by Django 3.2.10 on 2022-01-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1111-11-11'),
            preserve_default=False,
        ),
    ]
